### ISSUE TITLE
Wiki still states Blender 2.79 is the highest version supported.

### ISSUE THREAD

**Issue by cryptobench** [golemfactory/golem-wiki#20]
https://github.com/golemfactory/golem-wiki/blob/5cf896094546ebebac17347b9997b6b7e6585eea/Products/Brass-Beta/Being-a-Requestor.md 

The docs still states that files should be saved in blender 2.79 format, but the recent Golem release added support for 2.80.

Not sure if any other Blender related info is up-to-date.

**Comment by jamuszyn** [comment]
fixed, thanks
