### ISSUE TITLE
wrong version of pywin32 in nistalation from source on Windows

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-wiki#22]
new installation link:
https://github.com/mhammond/pywin32/releases/download/b223/pywin32-223.win-amd64-py3.6.exe

changes required on:
https://docs.golem.network/#/Products/Brass-Beta/Installation?id=windows-installation-from-source
https://github.com/golemfactory/golem/blob/develop/requirements-win.txt
https://docs.golem.network/#/Products/Brass-Beta/Installation?id=pywin32

**Comment by jamuszyn** [comment]
fixed in docs, thanks

**Comment by maaktweluit** [comment]
the name of the links are still the old version: `221` should be `223`, found this 2x

**Comment by jamuszyn** [comment]
fixed
